<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
	    <OutputType>WinExe</OutputType>
	    <RootNamespace></RootNamespace>
	    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	    <UseWindowsForms>true</UseWindowsForms>
	    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    </PropertyGroup>
    <ItemGroup>
        <Compile Update="Form1.Designer.vb">
            <DependentUpon>Form1.vb</DependentUpon>
        </Compile>
        <EmbeddedResource Include="Properties\licenses.licx" />
        <Compile Update="Properties\Resources.Designer.vb">
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
            <DesignTime>True</DesignTime>
        </Compile>
        <Compile Update="Properties\Settings.Designer.vb">
            <AutoGen>True</AutoGen>
            <DependentUpon>Settings.settings</DependentUpon>
            <DesignTimeSharedInput>True</DesignTimeSharedInput>
        </Compile>
    </ItemGroup>
    <ItemGroup>
	    <Content Include="MailMergeTemplate.rtf">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	    </Content>
        <Content Include="nwind.mdb">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="DevExpress.Win.RichEdit" Version="22.2.*" />
    </ItemGroup>
</Project>